// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankingSystem.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240319085106_KYCDocument")]
    partial class KYCDocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankingSystem.API.Models.Accounts", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccountCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AccountCreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccountModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AccountModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("AtmCardNum")
                        .HasColumnType("bigint");

                    b.Property<int>("AtmCardPin")
                        .HasColumnType("integer");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountCreatedBy");

                    b.HasIndex("AccountModifiedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankingSystem.API.Models.KycDocument", b =>
                {
                    b.Property<Guid>("KYCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GrandFatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("KYCId");

                    b.HasIndex("UserId");

                    b.ToTable("KycDocument");
                });

            modelBuilder.Entity("BankingSystem.API.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasMaxLength(50)
                        .HasColumnType("double precision");

                    b.Property<string>("TransactionRemarks")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("BankingSystem.API.Models.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("275fb55c-da3e-4920-9797-b31a6022bce6"),
                            Address = "Gothatar, Kathmandu",
                            CreatedAt = new DateTime(2024, 3, 19, 8, 51, 5, 900, DateTimeKind.Utc).AddTicks(780),
                            DateOfBirth = new DateTime(2002, 8, 20, 16, 58, 25, 342, DateTimeKind.Utc),
                            Email = "subritiaryal13@gmail.com",
                            Fullname = "Subriti Aryal",
                            ModifiedAt = new DateTime(2024, 3, 19, 8, 51, 5, 900, DateTimeKind.Utc).AddTicks(794),
                            Password = "$2b$10$kSUbd5TDt3gcqv6Q2RGT6O3gf8.2WBiTswxFec2vgN.rchPmZT.Wi",
                            UserType = 0,
                            Username = "subs"
                        },
                        new
                        {
                            UserId = new Guid("f920b0f2-e640-4cdf-9790-2cd53e4fc082"),
                            Address = "Kathmandu",
                            CreatedAt = new DateTime(2024, 3, 19, 8, 51, 5, 974, DateTimeKind.Utc).AddTicks(7033),
                            DateOfBirth = new DateTime(2000, 3, 23, 16, 58, 25, 342, DateTimeKind.Utc),
                            Email = "teller@gmail.com",
                            Fullname = "Teller Person",
                            ModifiedAt = new DateTime(2024, 3, 19, 8, 51, 5, 974, DateTimeKind.Utc).AddTicks(7048),
                            Password = "$2b$10$zhBu0FoNHiHIERvL.YESq.sGEu4.Va4UspYTxX3V6JvnPyRCisOt6",
                            UserType = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = new Guid("6ac1bb7a-d697-43d8-bcc9-9f915d53e4c8"),
                            Address = "Kathmandu",
                            CreatedAt = new DateTime(2024, 3, 19, 8, 51, 6, 76, DateTimeKind.Utc).AddTicks(5560),
                            DateOfBirth = new DateTime(2000, 3, 23, 16, 58, 25, 342, DateTimeKind.Utc),
                            Email = "accountUser@gmail.com",
                            Fullname = "Account Holder",
                            ModifiedAt = new DateTime(2024, 3, 19, 8, 51, 6, 76, DateTimeKind.Utc).AddTicks(5577),
                            Password = "$2b$10$n.oHXd8BRukdpIo2CxHOY.psOgGBATecrh8mpI6TtcXclkAKM/cai",
                            UserType = 0,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("BankingSystem.API.Models.Accounts", b =>
                {
                    b.HasOne("BankingSystem.API.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("AccountCreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingSystem.API.Models.Users", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("AccountModifiedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingSystem.API.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingSystem.API.Models.KycDocument", b =>
                {
                    b.HasOne("BankingSystem.API.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingSystem.API.Models.Transaction", b =>
                {
                    b.HasOne("BankingSystem.API.Models.Accounts", "Accounts")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
